
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/*"]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - uses: ryan-rozario/pipreqs-action-cpy@master

      - name: Show requirements.txt
        run: |
          cat requirements.txt

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - run: |
          python -m pip install --upgrade pip
          pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[tests]"

      - name: Run tests with coverage
        run: |
          pytest -k "not slow" --cov --cov-fail-under=100 --cov-report term-missing
